// Openings explorer — the full Lichess opening book (CC0) + SAN-line resolver.
//
// openings-db.json is generated by scripts/build-openings-list.mjs from the
// lichess-org/chess-openings TSVs: every named ECO line, with its mainline as
// canonical SAN. Each entry can be listed, searched and replayed move-by-move.
// The live opening label on the board still comes from
// window.api.openings.lookup(fen) — this dataset powers the browsable list.

import { Chess } from 'chessops/chess'
import { parseFen, makeFen, INITIAL_FEN } from 'chessops/fen'
import { parseSan, makeSan } from 'chessops/san'
import { makeUci } from 'chessops/util'
import OPENINGS_DB from './openings-db.json'

interface RawOpening {
  eco: string
  name: string
  san: string[]
}

export interface OpeningEntry {
  /** Stable id for React keys / selection. */
  id: string
  name: string
  /** ECO code for the listed mainline. */
  eco: string
  /** Family used to group/filter in the UI (by ECO volume). */
  group: string
  /** Mainline as SAN tokens, e.g. ['e4','e5','Nf3','Nc6','Bb5']. */
  line: string[]
}

/** A single resolved ply in an opening line. */
export interface LineMove {
  san: string
  uci: string
  /** FEN of the position AFTER this move. */
  fen: string
}

// ECO volume -> readable group label, in canonical A..E order.
const ECO_GROUP: Record<string, string> = {
  A: 'Flank & English',
  B: 'Semi-Open',
  C: 'Open & French',
  D: "Queen's Pawn",
  E: 'Indian'
}

function groupForEco(eco: string): string {
  return ECO_GROUP[eco[0]?.toUpperCase()] ?? 'Other'
}

// ---- Full opening book (generated; sorted by name) -----------------------

export const OPENINGS: OpeningEntry[] = (OPENINGS_DB as RawOpening[]).map((o, i) => ({
  id: `${o.eco}-${i}`,
  name: o.name,
  eco: o.eco,
  group: groupForEco(o.eco),
  line: o.san
}))

/** Filter-chip groups in canonical ECO order (A..E). */
export const OPENING_GROUPS: string[] = ['Flank & English', 'Semi-Open', 'Open & French', "Queen's Pawn", 'Indian']

/**
 * Resolve a SAN line into per-ply { san, uci, fen }. Walks from the initial
 * position; stops defensively on the first illegal/unparseable token (curated
 * data should never trip this, but never throw into the UI).
 */
export function resolveLine(sanLine: string[]): LineMove[] {
  const pos = Chess.fromSetup(parseFen(INITIAL_FEN).unwrap()).unwrap()
  const out: LineMove[] = []
  for (const token of sanLine) {
    const move = parseSan(pos, token)
    if (!move) break
    // Re-derive SAN so display is canonical (e.g. disambiguation/checks).
    const san = makeSan(pos, move)
    const uci = makeUci(move)
    pos.play(move)
    out.push({ san, uci, fen: makeFen(pos.toSetup()) })
  }
  return out
}
